import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex-grow">
          {children}
        </div>
        <footer className="w-full py-4 text-center text-gray-500 text-sm bg-white/50 backdrop-blur-sm border-t border-gray-200">
          <p>67162110310-5</p>
          <p className="mt-1 text-xs text-gray-400">
            Demo Credentials - Username: <span className="font-mono font-medium text-gray-600">siwakon</span> | Password: <span className="font-mono font-medium text-gray-600">Siwakon8!</span>
          </p>
        </footer>
      </body>
    </html>
  );
}
